title: 新闻小报
email: studying@duzui.onmicrosoft.com
description: > 
permalink: ':title/'
baseurl: "/sea-blog"
url: "https://lonelydrunk.github.io/sea-blog/" 

# Author settings
author: 语文小报
author-pic: lonelydrunk.png
about-author: 语文新闻小报制作。

# Contact links
email: studying@duzui.onmicrosoft.com
phone: +86 15750801507
website: https://lonelydrunk.github.io/sea-blog/
linkedin: #
github: lonelydrunk
twitter: 9uEDHX5d6xA6G3L#
facebook: profile.php?id=100049180174760#
instagram: #
pinterest: #

# Newsletter
mailchimp: 

# Disqus
discus_identifier: 

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 4
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
